name: 'AutoDev action'
description: 'Tries to merge all commits from a PR with the dev label into the dev branch'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  optimistic:
    required: false
    description: Ignores conflicts between branches and merges the remaining branches.
  token:
    required: true
    description: GitHub token of the user that should merge the PRs
  user:
    required: true
    description: E-mail address of the user that should merge the PRs
