on:
  push:
    branches-ignore:
      - dev
  pull_request:
    types: [labeled, unlabeled, opened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          token: ${{ secrets.DEV_PUSH_TOKEN }}
          user: ${{ secrets.DEV_PUSH_USER }}