name: Continuous Integration

on:
  push:
    branches-ignore:
      - dev
  pull_request:
    types: [labeled, unlabeled, opened, closed]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Tests
        run: npm test

      - name: Build Action
        run: npm run build

      - name: Execute Action
        uses: ./
        with:
          token: ${{ secrets.DEV_PUSH_TOKEN }}
          user: ${{ secrets.DEV_PUSH_USER }}
          optimistic: true
