on:
  pull_request:
    types: [ labeled ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}